blueprints/auth.py
import random
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session
from exts import mail
from flask_mail import Message
import string
from models import EmailcaptchaModel, UserModel
from exts import db
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            username = form.username.data
            password = form.password.data
            user = UserModel.query.filter_by(username=username, password=password).first()
            if not user:
                return redirect(url_for('auth.login'))
            else:
                # if check_password_hash(user.password, password):
                # cookie/session session 是经过加密存储在cookie中
                session['user_id'] = user.id

                return redirect('/')
        else:
            print(form.errors)
            # return redirect(url_for('auth.login'))
            return redirect('/')


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))



@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('regist.html')
    else:
        # print(request.form)
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password1.data
            # user = UserModel(email=email, username=username, password=generate_password_hash(password))
            user = UserModel(email=email, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.register'))


@bp.route('/mail/test')
def mail_test():
    message = Message(subject='邮箱测试', recipients=['2779328095@qq.com'], body='这是一条测试邮件')
    mail.send(message)
    return '成功'


@bp.route('/captcha/email')
def get_captcha_email():
    # /capt/cha/email/<email>
    # captcha/email?email=xxx@qq.com
    email = request.args.get('email')
    if not email:
        return jsonify({"code": 300, "message": "email输入失败", 'data': None})

    emali_captcha = EmailcaptchaModel.query.filter_by(email=email).first()
    if emali_captcha:
        print(emali_captcha.captcha)
        return jsonify({"code": 200, "message": "失败", 'data': emali_captcha.captcha})

    souurce = string.digits * 4
    captcha = ''.join(random.sample(souurce, 4))
    # message = Message(subject='知了验证码', recipients=[email], body=f"您的验证码是：{captcha}")
    # mail.send(message)
    print(captcha)
    email_captcha = EmailcaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({"code": 200, "message": "失败", 'data': '发送验证码'})

blueprints/qa.py
from flask import Blueprint, request, render_template, redirect, g, url_for
from .forms import Question, AnswerForm
from models import QuestionModel, UserModel, DetailModel
from exts import db
from decorators import login_required

bp = Blueprint('qa', __name__, url_prefix='/')


@bp.route('/')
def index():
    question = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()

    return render_template('index.html', questions=question)
    # return question


@bp.route('/qa/public', methods=['GET', 'POST'])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template('question.html')
    else:
        form = Question(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author_id=g.user.id)
            db.session.add(question)
            db.session.commit()
            return redirect('/')
        else:
            print(form.errors)
            return redirect(url_for('qa.public_question'))


@bp.route('/qa/detail/<qa_id>')
@login_required
def dq_datil(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template('detail.html', question=question)


@bp.route('/answer/public', methods=['POST'])
@login_required
def answer_public():
    form = AnswerForm(request.form)
    print(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        user_id = g.user.id
        answer = DetailModel(content=content, author_question_id=question_id, author_user_id=user_id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('qa.dq_datil', qa_id=question_id))
    else:
        print(form.errors)
        # print(request.form.get('question_id'), 'asss')
        return redirect(url_for('qa.dq_datil', qa_id=request.form.get('question_id')))


@bp.route('/search')
def search():
    # request.args.get() get获取
    # request.form post获取
    # <q> 带参数
    q = request.args.get('q')
    questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
    print(questions)
    return render_template('index.html', questions=questions)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.co m/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}-知了课堂问答平台</title>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img class="zhiliaologo" src="" alt="">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
                    <li><a href="{{ url_for('qa.public_question') }}">发布问答</a></li>
                </ul>
                <form class="navbar-form navbar-left" action="{{ url_for("qa.search") }}" method="get">
                    <div class="form-group">
                        <input name="q" type="text" class="form-control" placeholder="请输入关键字">
                    </div>
                    <button type="submit" class="btn btn-default">查找</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user %}
                        <li><a href="#">{{ user.username }}</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                    {% else %}
                        <li><a href="{{ url_for("auth.login") }}">登录</a></li>
                        <li><a href="{{ url_for("auth.register") }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main">
        {% block main %}
        {% endblock %}

    </div>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{#    <script src = '{{ url_for('static', filename = 'js/detail.js') }}'></script>#}
{% endblock %}

{% block title %}{{question.title}}{% endblock %}

{% block main %}
    <h3 class="page-title">{{ question.title }}</h3>
    <p class="question-info">
        <span>{{ question.author.username }}</span>
        <span>{{ question.create_time }}</span>
    </p>
    <hr>
    <p class="question-content"></p>
    <hr>
    <h4 class="comment-group-title">评论（{{ question.details | length }}）：</h4>
    <form action="{{ url_for('qa.answer_public') }}" method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" placeholder="请填写评论" name="content" class="form-control">
                <input type="hidden" name='question_id' value="{{ question.id }}">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id = 'pl'>评论()</button>
            </div>
        </div>
    </form>
    <ul class="comment-group">
        {% for answer in question.details %}
            <li>
                <div class="user-info">
                    <img class="avatar" src="{{ url_for('static',filename='images/zhiliao.png') }}" alt="">
                    <span class="username">{{ answer.author_user.username }}</span>
                    <span class="create-time">{{ answer.create_time }}</span>
                </div>
                <p class="comment-content">{{ answer.content }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}
{% block title %}
    首页
{% endblock %}

{% block main %}
    <ul class="question-ul">
        {% for question in questions %}
              <li>
                <div class="side-question">
                    <img class="side-question-avatar" src="{{ url_for('static',filename="images/zhiliao.png") }}" alt="">
                </div>
                <div class="question-main">
                    <p class="question-title"><a href="{{ url_for('qa.dq_datil', qa_id = question.id) }}">{{ question.title }}</a></p>
                    <p class="question-content">{{ question.content }}</p>
                    <p class="question-detail">
                        <span class="question-author">{{ question.author.username }}</span>
                        <span class="question-time">{{ question.create_time }}</span>
                    </p>
                </div>
            </li>
        {% endfor %}
        </ul>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block title %}登录{% endblock %}

{% block main %}
    <h3 class="page-title">登录</h3>
    <form  method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" name="username" placeholder="账号" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="密码" class="form-control">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">立即登录</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/question.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="">
{% endblock %}

{% block title %}发表问答{% endblock %}

{% block main %}
    <h3 class="page-title">发表问答</h3>
    <form method="post">
        <div class="form-container">
            <div class="form-group">
                <input name="title" type="text" placeholder="请输入标题" class="form-control">
            </div>
            <div class="form-group">
                <textarea name="content" placeholder="请输入内容"  class="form-control" rows="3"></textarea>
            </div>
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">提交</button>
            </div>
            </div>
    </form>
{% endblock %}

templates/regist.html
{% extends "base.html" %}

{% block title %}
     注册
{% endblock %}

{% block head %}
    <script src="{{ url_for('static', filename = 'jquery/jquery-3.3.1.js') }}"></script>
    <script src="{{ url_for('static', filename = 'js/register.js') }}"></script>
{% endblock %}

{% block main %}
    <h3 class="page-title">注册</h3>
    <form action="#" method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" name="email" placeholder="邮箱号码" class="form-control">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" id="captcha-btn">获取验证码</button>
            </div>
             <div class="form-group">
                <input type="text" name="captcha" placeholder="验证码" class="form-control">
            </div>
            <div class="form-group">
                <input type="text" name="username" placeholder="用户名" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password1" placeholder="密码" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password2" placeholder="重复密码" class="form-control">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">立即注册</button>
            </div>
        </div>
    </form>
{% endblock %}